- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "755"
  loop:
    - "{{ grafana_base_dir }}"
    - "{{ grafana_provisioning_dir }}"
    - "{{ grafana_datasources_dir }}"


- name: Deploy Prometheus datasource config
  ansible.builtin.template:
    src: prometheus-datasource.yml.j2
    dest: "{{ grafana_datasources_dir }}/prometheus.yml"
    owner: root
    group: root
    mode: "644" 
  notify: Restart Grafana

- name: Deploy Grafana docker compose file 
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ grafana_base_dir }}/compose.yml"
    owner: root
    group: root
    mode: "644"

- name: Start Grafana with compose 
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_base_dir }}"
    state: present